# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
                ('total_amount_to_be_paid_by_purchaser', models.IntegerField(default=0, help_text='This can be left as default, it will be automatically calculated')),
                ('comments', models.CharField(blank=True, help_text='Extra Comments made by Purchaser', max_length=200, null=True)),
                ('is_debtor', models.NullBooleanField(help_text='Select if Customer Owes Cash')),
            ],
            options={
                'verbose_name': 'Purchaser',
                'ordering': ['-date_sold'],
                'verbose_name_plural': 'Purchaser',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.IntegerField(default=1, help_text='Enter Quantity of Item Purchased')),
                ('item', models.ForeignKey(help_text='Type to Search or Select/Create an Item from Stock', on_delete=django.db.models.deletion.CASCADE, to='stock.Item')),
                ('purchaser', models.ForeignKey(help_text='Type to Search or Select/Create a Purchaser', on_delete=django.db.models.deletion.CASCADE, to='sales.Purchase')),
            ],
            options={
                'verbose_name': 'Items Purchased',
                'ordering': ['-purchaser'],
                'verbose_name_plural': 'Items Purchased',
            },
        ),
    ]
